spring:
  application.name: Account Service
  main.banner-mode: off

server:
  port: 8083
  tomcat.accesslog.enabled: true

management:
  endpoint.prometheus.enabled: true
  endpoints:
    web.base-path: /
    enabled-by-default: false
    web.exposure.include: prometheus
    web.path-mapping.prometheus: prometheus-metrics

springfox:
  documentation:
    swagger-ui.baseUrl: /apidoc
    open-api.v3.path: /apidoc/v3
    swagger.v2.path: /apidoc/v2

ardalo-platform:
  platform-gateway:
    base-url: http://localhost:8080/gateway/api
    platform-routes:
      - id: login
        definition: '{"uri":"http://account-service:8083","predicates":[{"name":"Path","args":{"arg0":"/login"}}],"filters":[{"name":"RewritePath","args":{"regexp":".+","replacement":"/api/pages/login"}}]}'
